### ISSUE TITLE
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class "OFFLINE\Sentry\Classes\Auth" not found

### ISSUE THREAD

**Issue by prhost** [OFFLINE-GmbH/oc-sentry-plugin#7]
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class "OFFLINE\Sentry\Classes\Auth" not found in /app/plugins/offline/sentry/classes/Context.php:30
2023-08-30T14:39:40.358181992Z Stack trace:
2023-08-30T14:39:40.358185992Z #0 /app/plugins/offline/sentry/Plugin.php(38): OFFLINE\Sentry\Plugin->getFrontendUser()
2023-08-30T14:39:40.358189325Z #1 /app/vendor/sentry/sentry/src/State/Hub.php(107): OFFLINE\Sentry\Plugin->OFFLINE\Sentry\{closure}(Object(Sentry\State\Scope))
2023-08-30T14:39:40.358192700Z #2 /app/plugins/offline/sentry/Plugin.php(49): Sentry\State\Hub->configureScope(Object(Closure))
2023-08-30T14:39:40.358195658Z #3 [internal function]: OFFLINE\Sentry\Plugin->OFFLINE\Sentry\{closure}(Object(Error))
2023-08-30T14:39:40.358198492Z #4 /app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/ReportableHandler.php(45): call_user_func(Object(Closure), Object(Error))
2023-08-30T14:39:40.358201325Z #5 /app/vendor/october/rain/src/Foundation/Exception/Handler.php(82): Illuminate\Foundation\Exceptions\ReportableHandler->__invoke(Object(Error))
2023-08-30T14:39:40.358204325Z #6 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(182): October\Rain\Foundation\Exception\Handler->report(Object(Error))
2023-08-30T14:39:40.358207408Z #7 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
2023-08-30T14:39:40.358210366Z #8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
2023-08-30T14:39:40.358213325Z

**Comment by tobias-kuendig** [comment]
Closed in #8
